name: Base64
on: 
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # personal access token
        token: ${{ secrets.BASE64_NAME }}
    - name: config git
      run: git config --global user.email "yxyusteven@gmail.com"&&git config --global user.name "git-yusteven"
    - name: Sleep
      run: 
        date; sleep 1s ;date
    - name: Write
      run:
        base64 url > long
        
    - name: check for changes
      run: git status
    - name: stage changed files
      run: git add long
    - name: commit changed files
      run: git commit -a -m"bot"
    - name: push code
      run: git push
