name: Base64
on: 
  push:
    branches: 
      - main
    paths: 'url'
  workflow_dispatch:
jobs:
  my-job:
    name: My Job
    runs-on: macos-latest
    steps:
    - name: Sleep
      run: 
        date;sleep 4m;date
    - name: Download
      run: 
        wget https://github.com/git-yusteven/openit/raw/main/url
    - name: Write
      run:
        base64 url
