name: Base64
on: 
  push:
    paths:
      - 'url'
  workflow_dispatch:
jobs:
  my-job:
    name: Base64 Encode
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # personal access token
        token: ${{ secrets.BASE64_NAME }}
    - name: config git
      run: git config --global user.email "yxyusteven@gmail.com"&&git config --global user.name "git-yusteven"
    - name: Write
      run: base64 url > long
    - name: check for changes
      run: git status
    - name: stage changed files
      run: git add .
    - name: commit changed files
      run: git commit -m"Change by GitHub action"
    - name: push code
      run: git push
    - name: connect jsdelivr
      run: curl https://purge.jsdelivr.net/gh/git-yusteven/openit@main/long
