name: Greeting from Mona
on: push

jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
    - name: 1
      run: 
        date ; sleep 1s ; date
    - name: 2
      run: 
        wget https://github.com/git-yusteven/openit/raw/main/url
    - name: 3
      run:
        base64 url > long
