name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  github-base64:
    runs-on: ubuntu-latest
    steps:
      - name: Run Workflow
        id: write_file
        uses: timheuer/base64-to-file@v1.1
        with:
          fileName: 'long'
          fileDir: './main'
          encodedString: ${{ secrets.SOME_ENCODED_STRING }}
