name: CI
on:
  push:
    branches:
      - master # 只在master上push触发部署
workflow_dispatch:
jobs:
github-metrics-personal:
build:
runs-on: ubuntu-latest
steps:- name: Run Workflow
id: write_fileuses
uses: timheuer/base64-to-file@v1.1
with: fileName: 'myTemporaryFile.txt'fileDir: './main/'token: ${{ secrets.SOME_ENCODED_STRING }}
- name: Some other step
uses: actions/someaction@master
with:
filelocation: ${{ steps.write_file.outputs.filePath }}
