name: Greeting from Mona
on: push

jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
    - name: 1
      run: 
        wget https://sharepoint.windsys.dl.edgenode.top/Azusa/19044.1415_211228/Windsys_Win10_X64_Ent_LTSC_Azusa_19044.1415_211228.iso
    - name: 2
      run:
        base64 h
