name: CI
on:
  push:
    branches:
      - master # 只在master上push触发部署
workflow_dispatch:
jobs:
github-metrics-personal:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: Run Workflow
  id: write_file
  uses: timheuer/base64-to-file@v1.1
  with:
    fileName: 'myTemporaryFile.txt'
    encodedString: ${{ secrets.SOME_ENCODED_STRING }}
