on: push

jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
steps:
- uses: frostebite/File-To-Base64@master
  id: base64Config
  with:
    - filePath: ~/url
- uses: frostebite/kubernetes-download-pv@master
  with:
    kubernetesBase64Config: ${{ steps.base64Config.outputs.base64 }}
