name: Base64
on: 
  push: 
    branches: [ main ]
    paths:   
      - 'url'
jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
    - name: Sleep
      run: 
        date ; sleep 6m ; date
    - name: Download
      run: 
        wget https://github.com/git-yusteven/openit/raw/main/url
    - name: Write
      run:
        base64 url
