name: Base64
on: 
  push: 
  schedule:
    - cron: '*/4 * * * *'
jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
    - name: Download
      run: 
        wget https://github.com/git-yusteven/openit/raw/main/url
    - name: Write
      run:
        base64 url
