name: CDN
on: 
   schedule:
      - cron: "5/20 * * * *"
   workflow_dispatch:
jobs:
  my-job:
    name: jsdelivr
    runs-on: ubuntu-latest
    steps:
    - name: long
      run: curl https://purge.jsdelivr.net/gh/git-yusteven/openit@main/long
    - name: Clash.yaml
      run: curl https://purge.jsdelivr.net/gh/git-yusteven/openit@main/Clash.yaml
    - name: HTTPS
      run: curl https://purge.jsdelivr.net/gh/git-yusteven/openit@main/https
