name: 'GitHub Actions Weather Bot'
on: 
  schedule:
    - cron: "0 * * * *"
  push:
    branches: "master"
  workflow_dispatch:
  jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
    - name: hh
       run: base64 h
